import React from 'react';import{createRoot}from'react-dom/client';import{Phone,MessageCircle,Menu,Wrench,Home,CheckCircle2,MapPin,Clock,ShieldCheck}from'lucide-react';import'./styles.css';

const PHONE='9594538117';
const services=['Bed Assembly','Wardrobe Assembly','Office Chair Assembly','Gaming Chair Assembly','Study Table Assembly','Dining Table Assembly','TV Unit Installation','Shoe Rack Assembly','Bookshelf Assembly','Cabinet Assembly','Sofa Assembly','Recliner Assembly','Furniture Dismantling','Furniture Reassembly','Furniture Fittings','Wall Mounting','Minor Furniture Repair'];
const areas=['Mumbai','Thane','Navi Mumbai','Kalyan','Dombivli','Diva','Mumbra','Kalwa','Mulund','Powai','Andheri East','Ghatkopar','Kanjurmarg'];
const wa=(text='Hello Furniture Fix, I need furniture assembly/installation service.')=>`https://wa.me/91${PHONE}?text=${encodeURIComponent(text)}`;

function Header(){return <><header><a className="brand" href="#"><span>FF</span>Furniture Fix</a><nav><a href="#services">Services</a><a href="#how">How It Works</a><a href="#areas">Service Areas</a><a href="#about">About</a><a href="#faq">FAQ</a></nav><div className="actions"><a className="btn ghost" href={'tel:+91'+PHONE}><Phone/>Call Now</a><a className="btn primary" href="#book">Book Service</a></div><Menu className="menu"/></header></>}

function App(){const submit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);const msg=`Hello Furniture Fix,\nI need furniture assembly/installation service.\n\nName: ${f.get('name')}\nLocation: ${f.get('area')}\nFurniture/Product: ${f.get('product')}\nService Required: ${f.get('service')}\nPreferred Date: ${f.get('date')}\nJob Details: ${f.get('details')}`;window.open(wa(msg),'_blank')};return <div><Header/>
<main>
<section className="hero"><div><p className="eyebrow">FURNITURE FIX • MUMBAI METROPOLITAN REGION</p><h1>Professional Furniture Assembly & Installation Service</h1><p className="lead">Professional doorstep furniture assembly, installation, dismantling and fitting services across Mumbai, Thane, Navi Mumbai and nearby areas.</p><div className="heroBtns"><a className="btn primary big" href="#book">Book a Service</a><a className="btn light big" href={'tel:+91'+PHONE}><Phone/>95945 38117</a><a className="btn whatsapp big" href={wa()} target="_blank"><MessageCircle/>WhatsApp</a></div><div className="notice"><ShieldCheck/>NO ADVANCE PAYMENT FOR NORMAL SERVICE BOOKINGS</div></div><div className="heroCard"><Wrench/><h3>Furniture service at your doorstep</h3><p>Beds • Wardrobes • Chairs • Tables • TV Units • Storage • Fittings • Minor Repair</p><div className="mini"><Clock/>8:00 AM – 10:00 PM • 7 Days</div></div></section>

<section className="trust">{['Professional Technicians','Doorstep Service','Easy Booking','Pay After Completion','7 Days Service'].map(x=><div><CheckCircle2/>{x}</div>)}</section>

<section id="services" className="section"><p className="eyebrow orange">OUR SERVICES</p><h2>What do you need help with?</h2><p className="sub">Choose a furniture service and send us the job details.</p><div className="grid">{services.map((s,i)=><article className="card" key={s}><div className="icon"><Wrench/></div><h3>{s}</h3><p>Professional doorstep {s.toLowerCase()} support for compatible furniture.</p><a href="#book">Book Service →</a></article>)}</div></section>

<section id="how" className="section alt"><p className="eyebrow orange">SIMPLE PROCESS</p><h2>How It Works</h2><div className="steps">{[['01','Choose Service','Select the furniture or service required.'],['02','Send Details','Share your location, preferred time and job details.'],['03','Technician Scheduling','We review the request and schedule based on job requirements and availability.'],['04','Complete & Pay','Check the completed work, then pay by UPI or cash.']].map(x=><article><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>

<section id="areas" className="section"><p className="eyebrow orange">SERVICE AREAS</p><h2>Furniture Assembly & Installation Across MMR</h2><div className="chips">{areas.map(a=><span><MapPin/>{a}</span>)}</div><p className="sub center">Service availability depends on location, job requirements and technician availability.</p></section>

<section id="book" className="booking"><div><p className="eyebrow">BOOK A SERVICE</p><h2>Tell us about your furniture job</h2><p>Submit the details below. This form opens WhatsApp with your information so you can send the request directly to Furniture Fix.</p><ul><li>No advance payment</li><li>Pay after job completion</li><li>UPI or Cash</li></ul></div><form onSubmit={submit}><label>Name*<input name="name" required placeholder="Your name"/></label><label>Mobile / WhatsApp*<input name="phone" required inputMode="tel" placeholder="10-digit mobile number"/></label><label>Service*<select name="service" required><option value="">Select service</option>{services.map(s=><option>{s}</option>)}</select></label><label>Furniture / Product*<input name="product" required placeholder="e.g. 3-door wardrobe"/></label><label>Area / Locality*<input name="area" required placeholder="e.g. Dombivli East"/></label><label>Preferred Date*<input name="date" type="date" required/></label><label className="full">Job Description<textarea name="details" rows="4" placeholder="Tell us about the product and work required"/></label><label className="check full"><input type="checkbox" required/> I confirm these details are correct and agree to be contacted regarding this service request.</label><button className="btn primary big full" type="submit">Send Booking on WhatsApp</button><small className="full">Online database booking and automatic Job ID will be enabled only after the backend is securely connected and tested.</small></form></section>

<section id="about" className="section alt"><p className="eyebrow orange">ABOUT</p><h2>Furniture Installation Made Simple</h2><p className="about">Furniture Fix provides furniture assembly, installation, dismantling, reassembly, furniture fittings, wall mounting and selected minor repair services across the Mumbai Metropolitan Region. We focus on clear communication, convenient booking, practical scheduling and payment after completion.</p></section>

<section id="faq" className="section"><p className="eyebrow orange">FAQ</p><h2>Common Questions</h2><div className="faqs"><details><summary>Do I need to pay in advance?</summary><p>No. Normal Furniture Fix service bookings are paid after job completion.</p></details><details><summary>Can I book through WhatsApp?</summary><p>Yes. Use the WhatsApp button or booking form on this website.</p></details><details><summary>Which areas do you serve?</summary><p>Mumbai, Thane, Navi Mumbai and supported nearby MMR areas. Availability depends on the job and technician schedule.</p></details><details><summary>Do you provide a service warranty?</summary><p>We do not advertise a service warranty. Concerns are assessed individually.</p></details></div></section>

<section className="final"><h2>Need Help With Furniture Assembly?</h2><p>Book professional furniture assembly and installation service at your location.</p><div><a className="btn primary big" href="#book">Book Service</a><a className="btn light big" href={'tel:+91'+PHONE}>Call 95945 38117</a></div><strong>No advance payment • Pay after job completion</strong></section>
</main>
<footer><div><b>Furniture Fix</b><p>Professional Furniture Assembly & Installation</p></div><div><b>Contact</b><p>+91 95945 38117</p><p>8:00 AM – 10:00 PM • 7 Days</p></div><div><b>Service Region</b><p>Mumbai Metropolitan Region, Maharashtra</p></div><p className="legal">Brand names and trademarks belong to their respective owners. Furniture Fix is an independent service provider unless explicitly stated otherwise.</p></footer>
<div className="mobileBar"><a href={'tel:+91'+PHONE}><Phone/>Call</a><a href="#book"><Home/>Book</a><a href={wa()} target="_blank"><MessageCircle/>WhatsApp</a></div></div>}
createRoot(document.getElementById('root')).render(<App/>);